learning_templates/basic_app/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = "basic_app"
urlpatterns = [
    path('', views.index, name='index'),
    url('other/', views.other, name='other'),
    url('relative/', views.relative, name='relative'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("basic_app/", include("basic_app.urls"))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {"text" : "hello world", "number" : 100}
    return render(request, "basic_app/index.html", context = context_dict)

def other(request):
    return render(request, "basic_app/other.html")

def relative(request):
    return render(request, "basic_app/relative_url_templates.html")

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg fixed-top bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'basic_app:index' %}">BRAND</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#"></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basic_app:other' %}">Other</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basic_app:relative' %}">Relative</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container mt-5">
      {% block body_block %}
      {% endblock %}
    </div>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load my_extras %}
{% block body_block %}
<h1>Welcome to index!</h1>
<h1>This is index.html page showing!</h1>
<h1>{{ text|cut:"world" }}</h1>
<h1>{{ number|add:100 }}</h1>
{% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<h1>Welcome to other!</h1>
<h1>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</h1>
<h1>Welcome to other!</h1>
<h1>Welcome to other!</h1>
{% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<h1>Welcome to relative url templates!</h1>
<a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
<a href="{% url 'admin:index' %}">THE ADMIN PAGE</a>
<a href="{% url 'basic_app:index' %}">LINK TO INDEX</a>
{% endblock %}